### ISSUE TITLE
RaspberryPi 4 exception after installation due to missing dependency library

### ISSUE THREAD

**Issue by Pythoniasm** [bitromortac/lndmanage#66] opened 2020-03-01 11:56 UTC
After pip installation of lndmanage I got an exception due to a missing dependency library with regards to numpy:

```bash
$ lndmanage
Traceback (most recent call last):
  File "/home/admin/scripts/lndmanage/py37venv/lib/python3.7/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/admin/scripts/lndmanage/py37venv/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/admin/scripts/lndmanage/py37venv/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/scripts/lndmanage/py37venv/bin/lndmanage", line 5, in <module>
    from lndmanage.lndmanage import main
  File "/home/admin/scripts/lndmanage/py37venv/lib/python3.7/site-packages/lndmanage/lndmanage.py", line 10, in <module>
    from lndmanage.lib.listchannels import ListChannels
  File "/home/admin/scripts/lndmanage/py37venv/lib/python3.7/site-packages/lndmanage/lib/listchannels.py", line 10, in <module>
    from lndmanage.lib.forwardings import get_forwarding_statistics_channels
  File "/home/admin/scripts/lndmanage/py37venv/lib/python3.7/site-packages/lndmanage/lib/forwardings.py", line 4, in <module>
    import numpy as np
  File "/home/admin/scripts/lndmanage/py37venv/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/admin/scripts/lndmanage/py37venv/lib/python3.7/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/home/admin/scripts/lndmanage/py37venv/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```

This was easily resolved by installing the library libatlas-base-dev via apt:

```bash
sudo apt-get install libatlas-base-dev
```

Please adjust the documentation for installation accordingly to not help new users at first installation.

**Comment by bitromortac** [comment] 2020-06-15 17:46
Thank you for the comment. I'll close this for now. This issue is not really lndmanage specific, so I didn't include it in the docs. The issue is easily searchable I think, so it's not lost.

**Closed as completed by bitromortac** 2020-06-15 17:46 UTC
