### ISSUE TITLE
Different KeyError when trying to rebalance

### ISSUE THREAD

**Issue by darwin** [bitromortac/lndmanage#10] opened 2019-04-19 21:39 UTC
Running 4d70bd8, previous KeyError #7 is fixed (actually the failing lookup gets skipped), but I hit another KeyError.

```
-------- Rebalance from 623641895831339008 to 623641895831339008 with 1255321 sats --------
Need to still rebalance 1255321 sat to reach the goal of 1255321 sat. Fees paid up to now: 0 msats.
Traceback (most recent call last):
  File "/root/lndmanage/lndmanage.py", line 131, in <module>
    main()
  File "/root/lndmanage/lndmanage.py", line 109, in main
    rebalancer.rebalance(args.channel, dry=not args.reckless, chunksize=args.chunksize)
  File "/root/lndmanage/lib/rebalance.py", line 329, in rebalance
    source_channel, target_channel, amt, invoice_r_hash, self.budget_sat, dry=dry)
  File "/root/lndmanage/lib/rebalance.py", line 88, in rebalance_two_channels
    channel_id_from, channel_id_to, amt_msat)
  File "/root/lndmanage/lib/routing.py", line 235, in get_routes_for_rebalancing
    channel_from = self.node.network.edges[chan_id_from]
KeyError: 623641895831339008
```

**Comment by bitromortac** [comment] 2019-04-20 06:17
Thank you! Concerning the KeyError, this is unexpected behavior of your lnd node. Somehow your node's network view doesn't know about your own channel. My node, for example, knows about ```self.node.network.edges[623641895831339008]```. You could check this on your node by ```lncli describegraph | grep -B1 -A22 623641895831339008```, which should give you the channel information that enters the node.network.edges dictionary.

Anyhow, you accidentally reported another known bug, namely that the rebalancer attempts to send and receive over the same channel, which of course makes no sense. I was missing a filter for the rebalancing channels, which is fixed by #11. This should also fix this issue.

**Comment by darwin** [comment] 2019-04-21 16:43
You are right. My `lncli describegraph` does not mention anything about `623641895831339008`.

**Comment by bitromortac** [comment] 2019-04-28 15:59
Related: lightningnetwork/lnd/issues/2241, ```lncli listchannels``` shows a channel already after 3 confirmations, whereas ```lncli describegraph``` shows it after 6 confirmations.

**Comment by darwin** [comment] 2019-04-28 17:46
That problematic channel `623641895831339008` is [very old](https://blockstream.info/tx/bd63bf9610d97b7598a9ad8ecd56ecba919d4fe1482d309e7c5a02fa599a4edb). I don't think it is because too few confirmations. But I agree that it must be a lnd bug.

**Comment by bitromortac** [comment] 2019-06-04 04:50
I'll close this for now as it seems to be an issue with lnd and didn't happen to me since a long time.

**Comment by bitromortac** [comment] 2019-06-04 04:50
Closed for now.

**Closed as completed by bitromortac** 2019-06-04 04:50 UTC
