### ISSUE TITLE
startup with zero channels

### ISSUE THREAD

**Issue by decentclock** [bitromortac/lndmanage#70] opened 2020-04-11 12:07 UTC
Hi! I just ran lndmanage, and get the following error. Let me know what else you need!

I have zero channels on my node. So I suspect it's complaining because of that. Let me know if I can take on a fix to this.

Running in interactive mode. You can type 'help' or 'exit'.
Initializing node interface.
Initializing network graph.
Reading graph from file.
Traceback (most recent call last):
  File "/Users/quentin/venv/bin/lndmanage", line 10, in <module>
    sys.exit(main())
  File "/Users/quentin/venv/lib/python3.7/site-packages/lndmanage/lndmanage.py", line 425, in main
    node = LndNode(config_file=config_file)
  File "/Users/quentin/venv/lib/python3.7/site-packages/lndmanage/lib/node.py", line 83, in __init__
    self.set_info()
  File "/Users/quentin/venv/lib/python3.7/site-packages/lndmanage/lib/node.py", line 295, in set_info
    active_only=False, public_only=False)
  File "/Users/quentin/venv/lib/python3.7/site-packages/lndmanage/lib/node.py", line 328, in get_open_channels
    channels_data = raw_channels.ListFields()[0][1]
IndexError: list index out of range

**Comment by bitromortac** [comment] 2020-04-15 05:11
Thanks for reporting, will be fixed in next release.

**Comment by bitromortac** [comment] 2020-04-19 07:13
Closing as duplicate of #67.

**Closed as completed by bitromortac** 2020-04-19 07:13 UTC
